import type {Recipe, Profile } from "./types"

export const defaultProfiles: Profile[] = [
  {
    id: "p1",
    userId: "2",
    name: "Martin",
    goal: null,
    age: null,
    height: null,
    avatarUrl: "oklch(0.985 0 0)",
    createdAt: new Date(),
  },
]

export const avatarColors = [
  "oklch(0.985 0 0)",
  "oklch(0.70 0 0)",
  "oklch(0.50 0 0)",
  "oklch(0.80 0.10 80)",
  "oklch(0.70 0.15 200)",
]


export const recipes: Recipe[] = [
  {
    id: "r1",
    title: "Bowl de pollo y arroz",
    description: "Un bowl nutritivo y facil de preparar con pollo grillado, arroz integral y vegetales frescos.",
    imageUrl: "/images/recipes/bowl-pollo.jpg",
    prepTime: 25,
    calories: 450,
    protein: 38,
    carbs: 45,
    fat: 12,
    servings: 1,
    ingredients: ["150g pechuga de pollo", "100g arroz integral", "50g brocoli", "1 tomate", "Salsa de soja", "Semillas de sesamo"],
    instructions: ["Cocinar el arroz integral segun el paquete.", "Grillar la pechuga de pollo con sal y pimienta.", "Cocinar el brocoli al vapor por 5 minutos.", "Armar el bowl: arroz, pollo cortado, brocoli y tomate.", "Agregar salsa de soja y semillas de sesamo."],
    tags: ["alto en proteina", "almuerzo"],
  },
  {
    id: "r2",
    title: "Avena overnight",
    description: "Desayuno rapido preparado la noche anterior. Cremoso, nutritivo y listo para llevar.",
    imageUrl: "/images/recipes/avena-overnight.jpg",
    prepTime: 5,
    calories: 320,
    protein: 14,
    carbs: 52,
    fat: 8,
    servings: 1,
    ingredients: ["50g avena", "200ml leche descremada", "1 banana", "1 cda miel", "Canela al gusto", "Frutos rojos"],
    instructions: ["Mezclar la avena con la leche en un frasco.", "Agregar miel y canela.", "Tapar y refrigerar toda la noche.", "Por la manana agregar banana y frutos rojos."],
    tags: ["desayuno", "rapido"],
  },
  {
    id: "r3",
    title: "Ensalada mediterranea",
    description: "Fresca ensalada con pepino, tomate, aceitunas y queso feta. Ideal para dias calurosos.",
    imageUrl: "/images/recipes/ensalada-med.jpg",
    prepTime: 10,
    calories: 280,
    protein: 12,
    carbs: 18,
    fat: 18,
    servings: 2,
    ingredients: ["2 tomates", "1 pepino", "100g queso feta", "Aceitunas negras", "Aceite de oliva", "Oregano", "Limon"],
    instructions: ["Cortar los tomates y el pepino en cubos.", "Agregar aceitunas y queso feta desmenuzado.", "Condimentar con aceite de oliva, limon y oregano.", "Mezclar y servir frio."],
    tags: ["ensalada", "bajo en calorias"],
  },
  {
    id: "r4",
    title: "Panqueques de banana",
    description: "Solo 3 ingredientes para un desayuno dulce y saludable, sin harina refinada.",
    imageUrl: "/images/recipes/panqueques-banana.jpg",
    prepTime: 15,
    calories: 250,
    protein: 16,
    carbs: 30,
    fat: 8,
    servings: 1,
    ingredients: ["1 banana madura", "2 huevos", "2 cdas avena", "Canela al gusto"],
    instructions: ["Pisar la banana con un tenedor.", "Agregar los huevos y la avena. Mezclar bien.", "Cocinar en sarten antiadherente a fuego medio.", "Dar vuelta cuando se formen burbujas.", "Servir con frutas o miel."],
    tags: ["desayuno", "sin gluten"],
  },
  {
    id: "r5",
    title: "Wrap de atun",
    description: "Almuerzo rapido y alto en proteinas con atun, vegetales crujientes y mostaza.",
    imageUrl: "/images/recipes/wrap-atun.jpg",
    prepTime: 10,
    calories: 350,
    protein: 30,
    carbs: 28,
    fat: 14,
    servings: 1,
    ingredients: ["1 tortilla integral", "1 lata atun en agua", "Lechuga", "Tomate", "1 cda mostaza", "Sal y pimienta"],
    instructions: ["Escurrir el atun y mezclarlo con la mostaza.", "Colocar lechuga y tomate sobre la tortilla.", "Agregar la mezcla de atun.", "Enrollar bien y cortar por la mitad."],
    tags: ["almuerzo", "rapido", "alto en proteina"],
  },
  {
    id: "r6",
    title: "Batido verde energizante",
    description: "Batido lleno de nutrientes con espinaca, banana y proteina. Perfecto post-entrenamiento.",
    imageUrl: "/images/recipes/batido-verde.jpg",
    prepTime: 5,
    calories: 220,
    protein: 18,
    carbs: 35,
    fat: 3,
    servings: 1,
    ingredients: ["1 banana", "Punado de espinaca", "200ml leche", "1 scoop proteina", "Hielo"],
    instructions: ["Agregar todos los ingredientes a la licuadora.", "Licuar hasta obtener textura cremosa.", "Servir inmediatamente."],
    tags: ["batido", "post-entreno"],
  },
  {
    id: "r7",
    title: "Pasta con salsa bolognesa light",
    description: "Version mas saludable de la clasica pasta bolognesa, con carne magra y muchos vegetales.",
    imageUrl: "/images/recipes/pasta-bolo.jpg",
    prepTime: 30,
    calories: 420,
    protein: 28,
    carbs: 48,
    fat: 12,
    servings: 2,
    ingredients: ["200g pasta", "150g carne molida magra", "1 cebolla", "2 tomates", "1 zanahoria", "Ajo", "Oregano"],
    instructions: ["Cocinar la pasta al dente.", "Saltear la cebolla y ajo picados.", "Agregar la carne molida y cocinar hasta dorar.", "Agregar tomates y zanahoria rallada.", "Condimentar con oregano, sal y pimienta.", "Cocinar 15 minutos a fuego bajo.", "Servir sobre la pasta."],
    tags: ["cena", "clasico"],
  },
  {
    id: "r8",
    title: "Tostada de palta y huevo",
    description: "Clasico desayuno saludable, rapido y lleno de grasas buenas y proteina.",
    imageUrl: "/images/recipes/tostada-palta.jpg",
    prepTime: 10,
    calories: 310,
    protein: 14,
    carbs: 22,
    fat: 20,
    servings: 1,
    ingredients: ["2 rebanadas pan integral", "1/2 palta", "1 huevo", "Sal, pimienta", "Chile en hojuelas (opcional)"],
    instructions: ["Tostar el pan.", "Pisar la palta con un tenedor, agregar sal y pimienta.", "Cocinar el huevo a gusto (pochado o frito).", "Untar la palta sobre el pan y colocar el huevo encima.", "Agregar chile en hojuelas al gusto."],
    tags: ["desayuno", "grasas saludables"],
  },
]

export const nutritionResponses: Record<string, string> = {
  proteinas: "Las proteinas son esenciales para la reparacion y crecimiento muscular. Se recomienda consumir entre 1.6-2.2g por kg de peso corporal si entrenas regularmente. Buenas fuentes: pollo, huevo, pescado, legumbres y lacteos.",
  calorias: "Las calorias son la unidad de energia que obtenemos de los alimentos. Para mantener peso, necesitas un balance entre lo que consumes y gastas. Un deficit de 300-500 kcal diarias es recomendable para perder peso de forma saludable.",
  carbohidratos: "Los carbohidratos son la principal fuente de energia. Prefiere carbohidratos complejos como avena, arroz integral, batata y legumbres. Evita los azucares refinados en exceso.",
  grasas: "Las grasas saludables son fundamentales para las hormonas y absorcion de vitaminas. Incluye palta, frutos secos, aceite de oliva y pescados grasos. Evita grasas trans.",
  hidratacion: "Se recomienda beber al menos 2-3 litros de agua al dia. Si entrenas, aumenta la ingesta. El agua ayuda a la digestion, transporte de nutrientes y regulacion de temperatura.",
  default: "Esa es una buena pregunta sobre nutricion. Te recomiendo consultar con un nutricionista para obtener una recomendacion personalizada. Mientras tanto, recuerda mantener una alimentacion variada y equilibrada.",
}
